# Site
title:              Justin Francis
bio:                '"All we have to decide is what to do with the time that is given us." - J.R.R. Tolkien'
description:        "My name is Justin Francis. I'm a soon-to-be graduate from the University of Utah in engineering. This is my site to show a little bit about me and my work."
reading_time:       true
words_per_minute:   100
logo:               'assets/img/logo.png'
background:         'assets/img/paintedLandscape.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://jphran.github.io

#for running 'jekyll serve'
# url:                http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   justinf

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              justinhfrancis@gmail.com
# twitter:            username
# facebook:           username
github-url:         jphran
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
# linkedin:          username
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
hackernews:         jphran

#TODO: figure out how to get hackster favicon loaded up
# hackster:           jfran

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
#TODO: figure out why removing '_site' from the exclude list made the assets populate
exclude: [_site, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, src, vendor/build, CNAME, LICENSE, Rakefile]
 