# Site
title:              Justin Francis
bio:                'I have a budding passion for embedded systems and control theory as well as data science. Basically, I like to make things move intelligently and with grace.'
description:        "I'm a soon-to-be graduate from the University of Utah as a cross-disciplinary engineer."
reading_time:       true
words_per_minute:   100
logo:               'assets/img/logo1.png'
background:         'assets/img/background/paintedLandscape.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://jphran.github.io

#for running 'jekyll serve'
# url:                http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#TODO: this is incredibly broken and outdated. Remove.
disqus_shortname:   justinf

# Social
google:
  #plus:            #username
  analytics:        UA-154847318-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              justinhfrancis@gmail.com
# twitter:            username
# facebook:           username
github-url:         jphran
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          justin-francis-758321121
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
# hackernews:         jphran
hackster:           jfran

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
#TODO: figure out why removing '_site' from the exclude list made the assets populate
exclude: [_site, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, src, vendor/build, CNAME, LICENSE, Rakefile]
 


######################Website Critique################################

## Sab notes ##
# About me -> about #
# uniform font #
# Logo sucks #
# remove bio line #
# make top of page button larger
# short -> contact #
# email -> email addy #
# background? need deets
# column text
# no project list, just a scrollable page
# move nave menu to right side
# implement a project menu on the right of a scrollable list


## Round two ##
# change nav menu and landing page to be same theme
# fixed menu
# project img on bottom of landing #
# facts (numbers, stats) near projects
# move hackster to social-links #
# cursor change (triangle)
# change default background color to blk
# have logo turn to go up/down 

##fixed menu
# remove clicakble logo and name on landing page
# name linkes to about me #


######################JOB HUNTING################################
## davies notes on jobs, not website

# Honeeybee robotics (pasadena)
# nasa jpl
# adept (owned by omron)
# omron (san ramone, ca)
# cat (catepillar)
# space x
# blue origin
# flir drones
# teal drones
# setpoint systems robotics
# ottobok
# samsung robotics

# center myself bewteen the topics (CS, EE, robo) (cross discplinary)
# I'm the keystone

# hit up caltech profs and tell them you're interested in robots and jpl (and grad school)
# maybe linda rogers at caltech/jpl
# "i'm intersted, shich route would be the best? SURF? SIP?"
# try backdooring it

# market the potential. show that you've worked with a touch of everything. put esp, pic, rpi, etc.




